services:
  app:
    image: app_songs:local
    container_name: app_songs
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - ps

  postgresql:
    image: postgres:14-alpine
    container_name: test_postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - ps

networks:
  ps: