basePath: /
definitions:
  Page:
    properties:
      page_count:
        type: integer
      text:
        type: string
    type: object
  handler.errorResponse:
    properties:
      message:
        type: string
    type: object
  handler.getTextOfSongHandler.responce:
    properties:
      pages:
        items:
          $ref: '#/definitions/Page'
        type: array
    type: object
  handler.statusResponse:
    properties:
      id:
        type: string
      status:
        type: string
    type: object
  model.AddSong:
    properties:
      group:
        type: string
      song:
        type: string
    type: object
  model.Song:
    properties:
      group:
        type: string
      id:
        type: string
      link:
        type: string
      release_date:
        type: string
      song:
        type: string
      text:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API Server for Songs
  title: Effective Mobile
  version: "1.0"
paths:
  /api/songs:
    get:
      description: Получить все песни
      operationId: api-songs-get
      parameters:
      - description: 'sort field: group, song, releaseDate, text or link'
        in: query
        name: field
        type: string
      - description: ASC or DESC
        in: query
        name: sort
        type: string
      - description: count songs on page
        in: query
        name: page
        type: integer
      - description: page number
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            items:
              $ref: '#/definitions/model.Song'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Получить все песни
      tags:
      - API для работы с песнями
    post:
      consumes:
      - application/json
      description: Создать Песню
      operationId: api-songs-post
      parameters:
      - description: название песни(song) и группы(group)
        in: body
        name: newSong
        required: true
        schema:
          $ref: '#/definitions/model.AddSong'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Создать Песню
      tags:
      - API для работы с песнями
  /api/songs/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить Песню по id
      operationId: api-songs-id-delete
      parameters:
      - description: song id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Удалить Песню по id
      tags:
      - API для работы с песнями
    get:
      consumes:
      - application/json
      description: Получить текст песни Песню по id
      operationId: api-songs-id-get
      parameters:
      - description: song id
        in: path
        name: id
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/handler.getTextOfSongHandler.responce'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Получить текст песни Песню по id
      tags:
      - API для работы с песнями
    put:
      consumes:
      - application/json
      description: Изменить Песню по id
      operationId: api-songs-id-put
      parameters:
      - description: song id
        in: path
        name: id
        type: string
      - description: новые поля песни
        in: body
        name: newSong
        required: true
        schema:
          $ref: '#/definitions/model.Song'
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            $ref: '#/definitions/handler.statusResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.errorResponse'
        default:
          description: ""
          schema:
            $ref: '#/definitions/handler.errorResponse'
      summary: Изменить Песню по id
      tags:
      - API для работы с песнями
swagger: "2.0"
